# Generated by Django 4.2.4 on 2023-09-17 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_save_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
