# Generated by Django 4.2.4 on 2023-09-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_save_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='post',
        ),
    ]
