# Generated by Django 4.2.4 on 2023-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_save_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='post',
            field=models.ManyToManyField(blank=True, default=None, related_name='save', to='post.post'),
        ),
    ]
