# Generated by Django 4.0.2 on 2023-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_save_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='post',
            field=models.ManyToManyField(blank=True, default=None, related_name='save', to='post.Post'),
        ),
    ]
