# Generated by Django 4.2.5 on 2023-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_relation_from_user_alter_relation_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('femail', 'femail'), ('fail', 'mail'), ('frefer not to say', 'prefer not to say')], max_length=50, null=True),
        ),
    ]
