# Generated by Django 4.2.5 on 2023-10-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='timestamp',
        ),
    ]
