# Generated by Django 4.2.4 on 2023-09-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
