# Generated by Django 4.2.4 on 2023-09-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
